spring: 
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: workmotion
    password: workmotion 
    driver-class-name: org.postgresql.Driver    
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate.ddl-auto: update
    show-sql: true
  flyway: 
    enabled: true
    url: jdbc:postgresql://localhost:5432/employee
    user: workmotion
    password: workmotion
    locations: classpath:db/migration
    baselineOnMigrate: false
